### ISSUE TITLE
Question about xml data structure

### ISSUE THREAD

**Issue by mitosagi** [hal-shu-sato/apm-data#1]
I have a few questions about the data structure of `plugins_list.xml` and `scripts_list.xml`.

`<type>`
- It seems that `<type>` is not necessary since it can be generated programmatically. Can I remove this?

`<file>`
- Is 'archivePath' for handling zip files that have a double folder?
- What does 'optional' do?

**Comment by hal-shu-sato** [comment]
> `<type>`
>
> It seems that `<type>` is not necessary since it can be generated programmatically. Can I remove this?

That's for sure.
Please do so.

> `<file>`
>
> Is 'archivePath' for handling zip files that have a double folder?

Yes, it is.
I plan to implement this instead of the file search, which is likely to be a bug, but I haven't implemented it yet.

> What does 'optional' do?

The files attributed as 'optional' are mainly created by the plugin or script when using.
APM uses it when uninstalling it.

**Comment by mitosagi** [comment]
Thanks for the answer. I think using `archivePath` is a good idea too.

I will close this issue now that it is resolved.

**Comment by mitosagi** [comment]
I would like to check some additional things.

`packages_list.xml`
- I see that detailURL is not being used, can I make it an option?

`core.xml`
- Can I remove aviutl110rc1 and aviutl110rc2 to prevent confusion?
- I plan to send out a PR highlighting the latest version. For this purpose, can I make the latest in extended editing 0.92 instead of 0.93rc1?

**Comment by hal-shu-sato** [comment]
> `packages_list.xml`
> 
> * I see that detailURL is not being used, can I make it an option?

Yes. It is an unnecessary element.
I thought of separating overview information and detail one before.
But I found that it is better to have all the information in `packages_list.xml`.

> `core.xml`
> 
> * Can I remove aviutl110rc1 and aviutl110rc2 to prevent confusion?
> * I plan to send out a PR highlighting the latest version. For this purpose, can I make the latest in extended editing 0.92 instead of 0.93rc1?

Yes, you can do both.
The data I made is very messy.
They are better.

**Comment by mitosagi** [comment]
Thanks for the answer. I would like to implement it based on this.
