### ISSUE TITLE
patch.aul install path問題

### ISSUE THREAD

**Issue by yumetodo** [hal-shu-sato/apm-data#123]
patch.aul r14のreadmeより

```
patch.aul r14
Copyright (c) 2021-2022 ePi
https://scrapbox.io/ePi5131/patch.aul

概要
    AviUtlや拡張編集のバグを直したり新機能を追加したりするプラグインです。

要求環境
    AviUtl version 1.10
    拡張編集 version 0.92

推奨環境
    OpenCLを使用可能なデバイス

導入
    patch.aul は aviutl.exe と同じディレクトリに配置します。
```

> patch.aul は aviutl.exe と同じディレクトリに配置します。

とあるにもかかわらず、apmを用いたときのインストール先がpluginsの下である

https://github.com/hal-shu-sato/apm-data/blob/38a2bca4521f69a2e149aecea05445dde1ec0223/v2/data/packages.xml#L808-L815

**Comment by yumetodo** [comment]
patch.aulをplugins配下に置くことについての、作者コメント

> 一応大丈夫な作りにはしていた気がしますが、推奨はしません
できるだけ速く読んでほしいからです

**Comment by hal-shu-sato** [comment]
そうですか…
完全に見逃していました…
データの修正は容易なのですが、apmの動作が上書きのみなので、インストールのみでは旧バージョンのファイルの削除ができないため、その辺りをどう処理するかは考えなければなりません。

**Comment by yumetodo** [comment]
cleanみたいな項目を作って消すファイルリストを指定できるようにするとかですかね・・・？

**Comment by yumetodo** [comment]
いや、need uninstallみたいなフラグがあれば、uninstall処理を走らせてplugins配下のpatch.aulを消せるはずですね・・・

https://github.com/hal-shu-sato/apm/blob/47a49d62f38de2bc171fca8755e5917c5271ed5e/src/package/package.js#L537-L552

**Comment by hal-shu-sato** [comment]
その機能は承知しています。
現状、ユーザーがアンインストールボタンを押さないと、その処理が行われないので、更新後のデータでインストールのみをしたとき、patch.aulが2つ存在することになります…
apm側の機能orフラグ追加等が必要な気がしてます……

**Comment by mitosagi** [comment]
確かに、インストール前にアンインストール処理を行うほうがいいですね。
それに加えてapmにAviUtl寄りのパス解決機能を実装すれば問題を解決できそうです。
手順としては、アンインストール時には、XMLデータに`/patch.aul`と記述されている場合、`/patch.aul`または`/plugins/patch.aul`に対する削除処理を行うようにします。インストール時には、素直に`/patch.aul`にファイルをコピーします。

**Comment by yumetodo** [comment]
@mitosagi さんの

>apmにAviUtl寄りのパス解決機能を実装すれば問題を解決できそうです。

が何を懸念しての機能なのかちょっと読み取れていないです。

---

基本的には常に一度アンインストールする必要もないと思うのでフラグの追加が穏当では無いでしょうか

**Comment by mitosagi** [comment]
> 何を懸念しての機能なのかちょっと読み取れていないです。

説明不足でした。フラグではなく常にアンインストールする理由ですが、私はapmを従来の手動でパッケージをインストールする方法と共存させたいと考えています。そうなると、すでにユーザーによってpatch.aul以外にもpluginフォルダ内外の意図していない側にインストールされているパッケージがある可能性がでてくるからです。

> [node.jsのパス解決の負の遺産](https://yosuke-furukawa.hatenablog.com/entry/2018/06/07/080335)

パス解決を柔軟にすることで逆に設定やコードが複雑になることがあるのですね。

**Comment by yumetodo** [comment]
ユーザーが行った操作はユーザーに責任があるべきであり、警告を出すくらいならともかく、勝手に削除しに行くのはそれはそれで意図しない挙動ではないかなと思っています。すくなくともパッケージマネージャの領分を超えているように思います。

やるとしたら競合状態として警告してapmとしてはインストールに失敗するようにすることでしょうか。
