### ISSUE TITLE
Add dependencies element

### ISSUE THREAD

**Issue by hal-shu-sato** [hal-shu-sato/apm-data#18]
Some packages need other packages.
So, I think it is necessary to check their dependencies.

What do you think about it?

Example
```xml
<packages>
  ...
  <package>
    <...>
    <dependencies>
      <dependency>SOME_PACKAGE_ID</dependency>
    </dependencies>
  </package>
  ...
</packages>
```

**Comment by mitosagi** [comment]
I'm thinking of adding it too, it would be useful to have packages like rikky_module installed automatically.
