### ISSUE TITLE
Mr-Ojii build版L-SMASH Works

### ISSUE THREAD

**Issue by yumetodo** [hal-shu-sato/apm-data#34]
## 名前

L-SMASH Works

## 概要

https://github.com/Mr-Ojii/L-SMASH-Works-Auto-Builds

にて**毎日**最新のffmpegを用いてビルドがされている。これにはMr-Ojiiがパッチを当てたbranchのものを含む。

## 説明

すでにPOPn氏のビルドのものがあるが、その後のffmepgの更新に追従できているとは言えない。

## 開発者

muken, HolyWu, Mr-Ojii氏

## 紹介ページURL
 
https://github.com/Mr-Ojii/L-SMASH-Works

## ダウンロードページURL

https://github.com/Mr-Ojii/L-SMASH-Works-Auto-Builds/releases

## ファイル名

see release

# 懸念点

- 毎日ビルドが回るのでそれに追従するCIをこちらで組んだ場合commit logがそれで埋まる
    - ffmepgの更新に毎日追従する必要はあるのか
        - その場合xmlのデータ構造に手を加えるなどしてcommit数を圧縮することが必要ではないか
            - 参考事例: AURでは`-git` sufixがついたパッケージが一般的にある: https://aur.archlinux.org/packages/ffmpeg-git/
    - 一方である一定期間過ぎたら取り込まれているべきではないか

**Comment by mitosagi** [comment]
ffmpegのバージョンを表示することができなくなる問題はありますが、プラグインをlatestページからダウンロードしてもらう方法ならCIなしで最新のビルドへ追従できそうです。

**Comment by hal-shu-sato** [comment]
そうですね。
追加で、インストール日をバージョン名にするオプションと機能を付ければ、ユーザーも更新するかどうか決めやすいと思います。
